### ISSUE TITLE
Similar plugins

### ISSUE THREAD

**Issue by itavero** [thomaspleasance/homebridge-zigbee2mqtt#2]
I didn't see an email address on your profile, but I was wondering if you were aware of some other plugins that might pursue the same or a similar goal as you are trying to achieve with this plugin:
* [homebridge-z2m](https://github.com/itavero/homebridge-z2m)
* [homebridge-zigbee-nt](https://github.com/madchicken/homebridge-zigbee-nt)

Maybe one of those plugins can benefit from your contribution as well. Of course, you're always free to create your own plugin that suits your needs better. 😉

**Comment by thomaspleasance** [comment]
There is no hinting there :) I'm just experimenting at the moment with the dev branch of zigbee2mqtt but I don't plan to release anything more than happy to contribute to the projects after I get a better understanding.

**Comment by itavero** [comment]
I wasn't sure what the purpose was of this repository (not even sure how I came across it a while back). 

By the way, even if you were considering releasing a plugin, please don't let me stop you.
Different people have different needs and, of course, it's an open platform.

Good luck exploring zigbee2mqtt and homebridge. 👍
